### ISSUE TITLE
Hover does not display over placeholders that use hex colors.

### ISSUE THREAD

**Issue by EwansXD** [AdvancedPlugins/Chat#196]
### Describe the bug

When the plugin parses prefixes for example %luckperms_prefix% or %vault_prefix%, if the prefix contains hex color codes it stops the hover from working.

### How to reproduce

Parse %luckperms_prefix% in formats with a hover

### Screenshots / Videos

Configuration section:
```
name:
  text: "%vault_prefix%%essentials_nickname%"
  hover:
    - '%vault_prefix%%player_name%'
    - '&3 | &7Rebirth: &f%rebirth_scoreboard%'
    - '&3 | &7Hits: &f%hits_value_formatted%'
    - ' '
    - '&3 | &bBalances'
    - '&3 | &a%money_balance_formatted% &2Money'
    - '&3 | &b%souls_balance_formatted% &3Souls'
    - '&3 | &e%essence_balance_formatted% &6Essence'
    - '&3 | &c%rivalcredits_balance_decimal% &4Credits'
    - ' '
    - '&3Click to message &b%player_name%&3!'
```

Output if user has the rank default with the prefix "&8[&7Explorer&8] &7":
![image](https://github.com/user-attachments/assets/557b2982-1ccf-496a-9f02-1e2d1471302c)

Output if user has the rank manager with the prefix "&8&l[&#e60000&l&lMANAGER&8&l] &#ff4f4f":
![image](https://github.com/user-attachments/assets/6f6666e7-fef7-4cd2-a904-9a64a24fe27e)
(Hover just does not work at all in this case)

### Server Log

https://mcpaste.io/3562019ddd29f38b
