### ISSUE TITLE
AdvancedChat player display name issue

### ISSUE THREAD

**Issue by GuavaDealer** [AdvancedPlugins/Chat#281]
### Describe the bug

so far i have only tested it on the mention part of the config, using `%player_displayname%` does not work while `%player_name%` does

Broken Example:
```yaml
mention:
  enabled: true
  char: "@"
  replacement: "<dark_aqua>@%player_displayname%</dark_aqua>"
  sound:
    name: "entity.player.levelup"
    volume: 1
    pitch: 1
```

### How to reproduce

simply use the `%player_displayname%` placeholder in the mention part of the `config.yml` not sure about anywhere else since i haven't tried it elsewhere

### Filled out form correct and using latest version

I confirm
