### ISSUE TITLE
Can't add customized lore lines for tags.

### ISSUE THREAD

**Issue by djcflores** [AdvancedPlugins/Chat#290]
### Describe the bug

Hello! I can't seem to add customize lore lines for each tag. I assume this is a bug since you can add customize lore lines on each chat color you make.

### How to reproduce

in the chatColorMenu.yml file, players can remove the lore lines under setting by adding # on it.

```
settings:
  # Slots in which colors can be displayed
  colorSlots: 10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34,37,38,39,40,41,42

  colorItem:
    name: "%color_name% &rChat Color"
    #lore: []
      #- '&7Click here to enable this chat color.'
```

and players can add customize lore lines for each chat color they added.

```
    dark_blue:
      format: "<dark_blue>%message%</dark_blue>"
      name: "&1Dark Blue"
      material: BRICK
      custom-model-data: 1050009
      lore:
        - ''
        - '&fꁒ Right-click to use this chat color.'
        - ''
        - '&fꀐꑴ'     
```

Do the same thing in the chatTagsMenu.yml file

```
settings:
  tagSlots: 10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34,37,38,39,40,41,42
  tagItem:
    name: "%tag% <white>Chat Tag"
    #lore:
    #  - '<gray>Click here to enable this chat tag.'
```

add lore section the tag like this

```
    axe:
      format: "<white>ꁠ"
      material: NETHER_BRICK
      custom-model-data: 1050000
      lore:
      - '&7This is a test lore'
```

But it does not work.

### Screenshots / Videos

![Image](https://github.com/user-attachments/assets/a67c6b36-fb3a-4b82-9e6f-e0a5412a375e)

![Image](https://github.com/user-attachments/assets/f53ef215-8367-4518-9ef3-9f79269385f6)

![Image](https://github.com/user-attachments/assets/f7f984d8-99ff-4df6-80bd-3e6953efe402)

### Filled out form correct and using latest version

I confirm
