### ISSUE TITLE
External emojis cloning properties from channel clickable

### ISSUE THREAD

**Issue by Schroddinger** [AdvancedPlugins/Chat#40]
### Describe the bug

The channel shows the following message on hover (which is correct).
![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/99b5f083-d1bc-487c-be88-ef86ebb5f558)

When an external plugin like Oraxen, uses emojis on the chat, said emoji will also display the channel message on hover.
It can also be clicked and it will execute the command to change channels.
![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/6784daa2-3550-41d0-9728-b54d6206da53)

### How to reproduce

1. Install a plugin like Oraxen to manage emojis.
2. In Oraxen's `settings.yml` set chat_handler to legacy mode.
3. In AdvancedChat configure hover and click actions in the channel prefix.

In Oraxen:
```yml
Chat:
  # If glyphs do not show up in chat, try setting this to LEGACY
  chat_handler: LEGACY # Valid once are MODERN & LEGACY
```

In AdvancedChat:
```yml
prefix:
  enabled: true
  channelPrefix: "%channel_color%[&f%channel_name%%channel_color%] "
  hover: 
    - '<yellow>Join %channel_id%</yellow> <white>%channel_name%</white>'
  click: 'RUN_COMMAND:/channel join %channel_id%'
```
