### ISSUE TITLE
Unfortunately, Mini-Message doesn't work

### ISSUE THREAD

**Issue by FlattestDisc108** [AdvancedPlugins/Chat#45]
### Describe the bug

When you use mini-message in chat formatting, it doesn't work and it lets your message stay as "%message%"

### How to reproduce

![image](https://github.com/AdvancedPlugins/Chat/assets/168830838/4c819c29-3275-4cf0-b8b8-23ea686d5613)
```
chat:
  text: '<gradient:#D00000:#FFBA08:#C5FFFD>%message%'
  hover: []
  click: ''
```

### Server Log

Nothing in server logs
