### ISSUE TITLE
Placeholder to quickly join a channel

### ISSUE THREAD

**Issue by Schroddinger** [AdvancedPlugins/Chat#5]
## Placeholder setup
Using `mini-message` it is possible to execute commands when clicking the channel name.
I hope to use this feature to allow players to quickly join the channel click without typing the command, but I would require a placeholder for the channel id, like `%channel_id%`. 
The current placeholder `%channel_name%` doesn't work for me as I use a custom emoji as the channel name.
You can see the channel id is `global` but the channel name is ``

```yml
channels:
  global: #Global chat
    name: ''
    # %channel_color%
    color: "<gray>"
    # Whether channel text should always be visible even when not in channel? You must have channel permission
    alwaysVisible: true
    # Only send to players in the same world
    sameWorld: false
    # Channel messages range
    # If set to 0, range won't be enabled. Set to any other number to enable.
    range: 0
    # Lowest priority will come first
    priority: 0
```

## The better setup
It would be great if this feature could be implemented by default without using mini-message.
Similar to how __Chat Format__ works.

### Setup with minimessage
```yml
prefix:
  enabled: true
  channelPrefix: "<click:run_command:'/channel join %channel_id%'>%channel_color%[&f%channel_name%%channel_color%]</click> "
```

### The better setup
```yml
prefix:
  enabled: true
  channelPrefix: "%channel_color%[&f%channel_name%%channel_color%] "
  hover:
    - 'Join %channel_name%'
  click: 'SUGGEST_COMMAND:!%channel_id% '
  #click: 'RUN_COMMAND:/channel join %channel_id%'
```

## Reference image of my setup
The name of the channel is a custom emoji and it would be great to just click it to execute an action `SUGGEST_COMMAND` or `RUN_COMMAND` for example.

![image](https://github.com/AdvancedPlugins/Chat/assets/11415969/6b887701-e347-41e6-b0b1-122ec6945684)
