### ISSUE TITLE
Channel Hover

### ISSUE THREAD

**Issue by itsDanny5555** [AdvancedPlugins/Chat#79]
### Describe the feature

I would like to Hover over my Channels and they have a individual Hover.
For now they have all the same prefix in the channels.yml

Like:
[Global] -> Hover: The Chat for all people. Click to join. And some other individual Informations about the Channel.
[StaffChat] -> Hover: The Chat for Staff.

**Comment by ThomasWega** [comment]
Can you try setting the channel names like so?

```yaml
channels:
  sc: #Staff chat
    name: "<hover:show_text:'<green>The channel for staff'>Staff Chat</hover>"
```
