### ISSUE TITLE
Chat Click (Bug Report)

### ISSUE THREAD

**Issue by ErenAslaNN** [AdvancedPlugins/Chat#83]
### Describe the bug

When we click on the message in the chat, the transfer does not take place correctly. Instead of the player's name appearing, the variable "%player_name%" appears.

### How to reproduce

Server ver: Purpur 1.20.4
Plugin ver: 1.1.8 

### Screenshots / Videos

https://prnt.sc/kteHoq9hp03-
https://prnt.sc/lecxAiB_0bV0

**Comment by ThomasWega** [comment]
Can you try setting the channel names like so?

```yaml
channels:
  sc: #Staff chat
    name: "<hover:show_text:'<green>The channel for staff'>Staff Chat</hover>"
```
